services:
    iotscan:
        container_name: IOTScan
        cap_add:
            - NET_RAW
            - NET_ADMIN
        network_mode: host
        privileged: True
        environment:
            - INTERFACE=wlan0
            # Specify first 3 octets for any IP in subnet or all four for a specific IP
            - SOURCEIP=127.0.0.1
            - PACKETCNT=1000
        image: ghcr.io/moyito2604/iotscan:latest
