services:
    iotscan:
        container_name: IOTScan
        cap_add:
            - NET_RAW
            - NET_ADMIN
        network_mode: host
        privileged: True
        environment:
            - INTERFACE=wlan0
            - SOURCEIP=
            - PACKETCNT=1000
        image: ghcr.io/moyito2604/iotscan:latest
